/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 hongo.gltf --transform 
Files: hongo.gltf [4.17KB] > C:\Users\USUARIO\Desktop\PruebasBlender\hongo-transformed.glb [44.94KB] (-978%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/hongo-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0, 1.875, 0]} scale={[1, 1.014, 1]}>
        <mesh geometry={nodes.Cube_1.geometry} material={materials.Material} />
        <mesh geometry={nodes.Cube_2.geometry} material={materials.cabeza} />
        <mesh geometry={nodes.Cube_3.geometry} material={materials.ojos} />
      </group>
    </group>
  )
}

useGLTF.preload('/hongo-transformed.glb')
