/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 illustration3D.gltf --transform 
Files: illustration3D.gltf [13MB] > D:\Paginas_Web\portfolio_pyecom\diseños3d\Illustration\illustration3D-transformed.glb [1.53MB] (88%)
Author: Denriansyah Sani Rangkuti (https://sketchfab.com/abadi)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/painter-3d-charater-illustration-44d42d4e48704c3b8b3f912bcd316bb6
Title: Painter 3D Charater Illustration
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/illustration3D-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <primitive object={nodes.GLTF_created_0_rootJoint} />
      <mesh geometry={nodes.Object_4.geometry} material={materials['Kayu.004']} position={[0.313, 4.35, 0.884]} rotation={[0.648, -0.294, 0.405]} scale={[0.128, 0.486, 0.128]} />
      <mesh geometry={nodes.Object_8.geometry} material={materials['Wadah.002']} position={[-2.028, 4.226, -0.352]} rotation={[0.062, 0.074, 0.108]} scale={0.329} />
      <mesh geometry={nodes.Object_10.geometry} material={materials.Cat_hijau} position={[-1.627, 4.259, -0.105]} rotation={[-1.243, 1.508, -1.753]} scale={[-4.066, 4.066, 4.066]} />
      <mesh geometry={nodes.Object_12.geometry} material={materials.Floor} scale={12.091} />
      <mesh geometry={nodes.Object_18.geometry} material={materials.Badan} position={[-0.391, 0.03, -1.648]} rotation={[0, -0.268, 0]} scale={1.358} />
      <mesh geometry={nodes.Object_20.geometry} material={materials.tALI} position={[-0.391, 0.03, -1.648]} rotation={[0, -0.268, 0]} scale={1.358} />
      <mesh geometry={nodes.Object_87.geometry} material={materials['Rambut.002']} position={[-0.36, 7.319, -1.76]} rotation={[0, -0.268, 0]} scale={0.207} />
      <mesh geometry={nodes.Object_89.geometry} material={materials.Mata} position={[-0.358, 7.225, -1.269]} rotation={[0, -0.268, 0]} scale={[0.038, 0.061, 0.027]} />
      <mesh geometry={nodes.Object_91.geometry} material={materials.Hidung} position={[-0.358, 7.319, -1.77]} rotation={[0, -0.268, 0]} scale={0.228} />
      <mesh geometry={nodes.Object_93.geometry} material={materials['Masker.003']} position={[-0.364, 7.319, -1.745]} rotation={[0, -0.268, 0]} scale={0.236} />
      <mesh geometry={nodes.Object_95.geometry} material={materials['Sepatu.001']} position={[-0.097, 0.219, -1.574]} rotation={[0, -0.268, 0]} scale={[0.21, 0.189, 0.189]} />
      <mesh geometry={nodes.Object_97.geometry} material={materials['Sepatu.002']} position={[-0.097, 0.219, -1.574]} rotation={[0, -0.268, 0]} scale={[0.21, 0.189, 0.189]} />
      <mesh geometry={nodes.Object_99.geometry} material={materials['Kayu.006']} position={[-0.391, 4.08, -1.648]} rotation={[0, -0.268, 0]} scale={1.358} />
      <mesh geometry={nodes.Object_100.geometry} material={materials.Kursi_Besi} position={[-0.391, 4.08, -1.648]} rotation={[0, -0.268, 0]} scale={1.358} />
      <mesh geometry={nodes.Object_102.geometry} material={materials.Besi} position={[-0.391, 1.714, -1.648]} rotation={[0, -0.268, 0]} scale={[0.079, 0.332, 0.079]} />
      <mesh geometry={nodes.Object_104.geometry} material={materials.Telinga} position={[0.169, 7.159, -1.677]} rotation={[1.437, -0.037, 0.266]} scale={[0.149, 0.028, 0.149]} />
      <mesh geometry={nodes.Object_106.geometry} material={materials['Rambut.001']} position={[-0.5, 0.151, -1.254]} rotation={[Math.PI / 2, 0, 0.268]} scale={49.771} />
      <mesh geometry={nodes.Object_108.geometry} material={materials['Rambut.003']} position={[-0.488, 0.03, -1.296]} rotation={[Math.PI / 2, 0, 0.268]} scale={49.771} />
      <mesh geometry={nodes.Object_110.geometry} material={materials.Kaki} position={[-0.069, 0.683, -1.566]} rotation={[0, -0.268, 0]} scale={0.268} />
      <mesh geometry={nodes.Object_112.geometry} material={materials['Baju.003']} position={[-0.392, 3.808, -1.646]} rotation={[0, -0.268, 0]} scale={0.091} />
      <mesh geometry={nodes.Object_114.geometry} material={materials.Celana} position={[-0.379, 4.051, -1.694]} rotation={[0, -0.268, 0]} scale={0.486} />
      <mesh geometry={nodes.Object_116.geometry} material={materials['Besi.002']} position={[-0.391, 0.409, -1.648]} rotation={[0, -0.268, 0]} scale={1.358} />
      <mesh geometry={nodes.Object_119.geometry} material={materials.material} position={[-4.557, 0.101, -4.505]} rotation={[0, 0.325, 0]} scale={1.299} />
      <mesh geometry={nodes.Object_120.geometry} material={materials.Vas_atas} position={[-4.557, 0.101, -4.505]} rotation={[0, 0.325, 0]} scale={1.299} />
      <mesh geometry={nodes.Object_123.geometry} material={materials.Tangkai_01} position={[-4.745, 1.447, -3.809]} rotation={[0.003, 0.313, -0.087]} scale={0.179} />
      <mesh geometry={nodes.Object_125.geometry} material={materials.Daun_1_01} position={[-3.093, 2.348, -4.679]} rotation={[-1.505, 0.854, -0.398]} scale={[-0.302, 0.302, 0.302]} />
      <mesh geometry={nodes.Object_128.geometry} material={materials.Daun_2_01} position={[-3.118, 2.046, -5.111]} rotation={[-1.972, 1.207, 0.417]} scale={0.293} />
      <mesh geometry={nodes.Object_132.geometry} material={materials.Meja} position={[-1.607, 3.393, 4.438]} rotation={[0, 0.184, 0]} scale={1.243} />
      <mesh geometry={nodes.Object_134.geometry} material={materials['Apel.001']} position={[-1.846, 3.706, 4.635]} rotation={[-0.378, 0.23, 0.514]} scale={0.168} />
      <mesh geometry={nodes.Object_137.geometry} material={materials.Mangkok} position={[-1.636, 3.609, 4.489]} rotation={[0, 0.184, 0]} scale={0.642} />
      <mesh geometry={nodes.Object_139.geometry} material={materials['Pisang.001']} position={[-1.827, 4.009, 4.055]} rotation={[0.611, 0.746, -0.46]} scale={0.255} />
      <mesh geometry={nodes.Object_141.geometry} material={materials.Kain} position={[-1.534, 3.512, 4.419]} rotation={[0, 0.327, 0]} scale={1.508} />
      <mesh geometry={nodes.Object_143.geometry} material={materials['Jeruk.001']} position={[-1.362, 3.721, 4.659]} rotation={[0, 0.184, 0]} scale={0.169} />
      <mesh geometry={nodes.Object_146.geometry} material={materials.Frame_canvas} position={[2.05, 3.27, 1.768]} rotation={[-2.95, -0.261, -3.091]} scale={1.358} />
      <mesh geometry={nodes.Object_148.geometry} material={materials['Frame_canvas.002']} position={[2.05, 3.27, 1.768]} rotation={[-2.95, -0.261, -3.091]} scale={[1.15, 0.131, 0.065]} />
      <mesh geometry={nodes.Object_150.geometry} material={materials.Canvas} position={[2.183, 5.013, 1.893]} rotation={[0.204, 0.267, -0.059]} scale={[1.545, 1.732, 0.113]} />
      <mesh geometry={nodes.Object_153.geometry} material={materials.material_42} position={[2.195, 6.99, 2.299]} rotation={[1.702, -0.036, 2.878]} scale={[0.062, 0.031, 0.062]} />
      <mesh geometry={nodes.Object_156.geometry} material={materials['Vas.001']} position={[4.266, 0.101, -4.381]} rotation={[0, -0.197, 0]} scale={1.299} />
      <mesh geometry={nodes.Object_160.geometry} material={materials.Daun_2_02} position={[2.869, 1.948, -5.28]} rotation={[-2.076, -1.175, -0.64]} scale={[-0.32, 0.32, 0.32]} />
      <mesh geometry={nodes.Object_162.geometry} material={materials.Daun_2_03} position={[2.869, 1.948, -5.28]} rotation={[-2.076, -1.175, -0.64]} scale={[-0.32, 0.32, 0.32]} />
      <mesh geometry={nodes.Object_164.geometry} material={materials.Tangkai_02} position={[4.354, 1.586, -4.454]} rotation={[0, -0.197, 0]} scale={[-0.239, 0.239, 0.239]} />
      <mesh geometry={nodes.Object_166.geometry} material={materials.Daun_1_02} position={[5.631, 2.34, -3.807]} rotation={[-0.958, 0.69, -1.158]} scale={[-0.302, 0.302, 0.302]} />
      <skinnedMesh geometry={nodes.Object_85.geometry} material={materials.Kepala} skeleton={nodes.Object_85.skeleton} position={[-0.391, 3.808, -1.648]} rotation={[0, -0.268, 0]} scale={1.358} />
    </group>
  )
}

useGLTF.preload('/illustration3D-transformed.glb')
